apiVersion: apps/v1
kind: Deployment
metadata:
  name: nest-app-deployment
  labels:
    app: nest-app
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: nest-app
  template:
    metadata:
      labels:
        app: nest-app
    spec:
      containers:
      - name: nest-container
        image: mahadali123/nest-app:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        # ConfigMap aur Secret se variables yahan inject ho rahe hain
        env:
          - name: PORT
            valueFrom:
              configMapKeyRef:
                name: nest-app-config
                key: PORT
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: nest-app-secret
                key: DB_PASSWORD
        readinessProbe:
          httpGet:
            path: /api/hello
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          limits:
            cpu: "500m"
            memory: "256Mi"
          requests:
            cpu: "200m"
            memory: "128Mi"